services:
  oshin:
    image: oshin:latest
    volumes:
      - ./app:/root/workspace/
    command: bash -c "cd ~/workspace/ros2_ws && rosdep install -i --from-path src --rosdistro rolling -y && colcon build --packages-select py_pubsub && echo "hola_mundo!" && source install/setup.bash && ros2 run py_pubsub talker"
    tty: true
    
  oshin2:
    image: oshin:latest
    volumes:
      - ./app:/root/workspace/
    command: bash -c "cd ~/workspace/ros2_ws && rosdep install -i --from-path src --rosdistro rolling -y && colcon build --packages-select py_pubsub && echo "hola_mundo!" && source install/setup.bash && ros2 run py_pubsub listener"
    tty: true
    
  # gzweb:
  #   image: vasilescur/gzweb-rosssh
  #   tty: true
  #   ports:
  #     - 8080:8080

# Usage
# First, do:
# docker pull vasilescur/gzweb-rosssh
# Then, run with:
# docker run -t -d -p 8080:8080 gzweb-rosssh
# Use your browser to access the running web interface at localhost:8080.
# Building
# To build the image, run:
# docker build -t vasilescur/gzweb-rosssh .

