services:
  oshin:
    # image: arm64v8/ros
    image: oshin:latest
    volumes:
      - ./app:/root/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY}
    command: bash -c "cd /root/workspace && echo "hola_mundo!" && tail -F anything"
    tty: true
    
  gzweb:
    image: vasilescur/gzweb-rosssh
    tty: true
    ports:
      - 8080:8080

# Usage
# First, do:
# docker pull vasilescur/gzweb-rosssh
# Then, run with:
# docker run -t -d -p 8080:8080 gzweb-rosssh
# Use your browser to access the running web interface at localhost:8080.
# Building
# To build the image, run:
# docker build -t vasilescur/gzweb-rosssh .

